from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results" / "okutama_cptr"


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def test_cptr_portable_inventory_matches_files() -> None:
    manifest = read_json(RESULTS / "evidence_manifest.json")
    actual = {
        path.name
        for path in RESULTS.iterdir()
        if path.is_file() and path.name != "evidence_manifest.json"
    }
    assert manifest["schema_version"] == 2
    assert manifest["study"] == "okutama_cptr_development"
    assert manifest["hash_algorithm"] == "sha256"
    assert manifest["text_encoding"] == "utf-8"
    assert manifest["text_line_endings"] == "LF"
    assert manifest["artifact_count"] == len(actual)
    assert set(manifest["artifacts"]) == actual
    for name, evidence in manifest["artifacts"].items():
        path = RESULTS / name
        assert b"\r" not in path.read_bytes()
        assert sha256_file(path) == evidence["sha256"]
        assert path.stat().st_size == evidence["size_bytes"]


def test_cptr_decision_matches_grouped_evidence() -> None:
    decision = read_json(RESULTS / "development_decision.json")
    uncertainty = read_json(RESULTS / "uncertainty.json")
    headline = pd.read_csv(RESULTS / "headline_metrics.csv").set_index(["scope", "model"])
    assert decision["status"] == "OKUTAMA_CPTR_DEVELOPMENT_LOCKED_NO_PROMOTION"
    assert decision["promotion_passed"] is False
    assert decision["calibration_samples_read"] == 0
    assert decision["confirmation_samples_read"] == 0
    assert (
        headline.loc[("development_validation", "centre_short_parts"), "macro_f1"]
        > headline.loc[("development_validation", "v3_temporal_baseline"), "macro_f1"]
    )
    assert (
        headline.loc[("grouped_crossfit_oof", "centre_short_parts"), "macro_f1"]
        < headline.loc[("grouped_crossfit_oof", "v3_temporal_baseline"), "macro_f1"]
    )
    assert uncertainty["crossfit_oof_cluster_bootstrap"]["macro_f1"]["ci_95_low"] < 0.0
    assert uncertainty["crossfit_oof_cluster_bootstrap"]["macro_f1"]["ci_95_high"] > 0.0
    assert uncertainty["crossfit_oof_exact_group_swap"]["permutations"] == 2048


def test_cptr_component_and_crossfit_tables_are_complete() -> None:
    components = pd.read_csv(RESULTS / "component_ablation.csv")
    fold_seed = pd.read_csv(RESULTS / "fold_seed_metrics.csv")
    expected_components = {
        "raw_trajectory",
        "camera_compensated_trajectory",
        "centre_short",
        "dual_clock",
        "dual_clock_specialized",
        "centre_short_trajectory",
        "centre_short_parts",
        "integrated_cptr",
        "counterfactual_original",
        "counterfactual_refined",
        "masked_initialisation",
        "siglip_posture_specialist",
        "group_dro",
        "top_block_lora",
    }
    assert set(components["component_id"]) == expected_components
    lineage_columns = {
        "run_status",
        "summary_sha256",
        "request_payload_sha256",
        "request_file_sha256",
        "model_module_sha256",
        "neural_module_sha256",
        "feature_module_sha256",
        "training_module_sha256",
        "runner_sha256",
        "grid_sha256",
        "grid_lock_sha256",
    }
    assert lineage_columns.issubset(components.columns)
    assert (
        not components[["summary_sha256", "request_payload_sha256", "request_file_sha256"]]
        .isna()
        .any()
        .any()
    )
    assert components["model_module_sha256"].dropna().nunique() >= 2
    individual = fold_seed[
        fold_seed["fold"].isin(["0", "1", "2", "3", "4"])
        & fold_seed["seed"].isin(["42", "43", "44", "45", "46"])
    ]
    assert len(individual) == 25
    assert len(fold_seed[fold_seed["seed"].eq("ensemble")]) == 5

    contract = read_json(RESULTS / "provenance.json")["crossfit_contract_audit"]
    assert contract["status"] == "VERIFIED_WITH_HISTORICAL_SCHEMA_LIMITATIONS"
    assert contract["requests_verified"] == 25
    assert contract["candidate_grid_matches_adaptive_lock"] is True


def test_public_cptr_text_has_no_internal_or_generation_markers() -> None:
    paths = (
        ROOT / "README.md",
        ROOT / "docs" / "OKUTAMA_CPTR_DEVELOPMENT.md",
        RESULTS / "README.md",
    )
    markers = (
        "as an " + "ai",
        "chat" + "gpt",
        "clau" + "de",
        "generated by " + "ai",
        "internal " + "note",
        "todo",
        "tbd",
        "placeholder",
    )
    local_user_prefix = "c:" + chr(92) + "users" + chr(92)
    local_user_prefix_forward = "c:" + "/" + "users" + "/"
    local_file_scheme = "file" + "://"
    for path in paths:
        text = path.read_text(encoding="utf-8").casefold()
        assert not any(marker in text for marker in markers)
        assert local_user_prefix not in text
        assert local_user_prefix_forward not in text
        assert local_file_scheme not in text
