from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results" / "vcoco_v3"


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def test_portable_evidence_inventory_matches_files() -> None:
    manifest = read_json(RESULTS / "evidence_manifest.json")
    actual = {
        path.name
        for path in RESULTS.iterdir()
        if path.is_file() and path.name != "evidence_manifest.json"
    }
    assert manifest["status"] == "VCOCO_V3_PORTABLE_EVIDENCE_COMPLETE"
    assert set(manifest["artifacts"]) == actual
    for name, evidence in manifest["artifacts"].items():
        path = RESULTS / name
        assert sha256_file(path) == evidence["sha256"]
        assert path.stat().st_size == evidence["size_bytes"]


def test_confirmation_metrics_and_routing_endpoints_align() -> None:
    metrics = pd.read_csv(RESULTS / "confirmation_metrics.csv").set_index("family")
    routing = pd.read_csv(RESULTS / "confirmation_routing_curve.csv")
    uncertainty = read_json(RESULTS / "confirmation_uncertainty.json")

    assert metrics.loc["teacher", "macro_f1"] > metrics.loc["static", "macro_f1"]
    assert metrics.loc["hybrid_budget_0.5", "macro_f1"] > metrics.loc["static", "macro_f1"]
    assert metrics.loc["hybrid_budget_0.5", "macro_f1"] < metrics.loc["teacher", "macro_f1"]
    assert routing["macro_f1"].is_monotonic_increasing
    assert routing.iloc[0]["macro_f1"] == metrics.loc["classification_student", "macro_f1"]
    assert routing.iloc[-1]["macro_f1"] == metrics.loc["teacher", "macro_f1"]
    assert uncertainty["teacher"]["macro_f1"]["ci_95_low"] > 0.0
    assert uncertainty["hybrid_budget_0.5"]["macro_f1"]["ci_95_low"] > 0.0


def test_public_v3_text_has_no_internal_or_generation_markers() -> None:
    paths = (
        ROOT / "docs" / "VCOCO_V3_MOTION_IDENTIFIABILITY.md",
        RESULTS / "README.md",
    )
    markers = (
        "as an " + "ai",
        "chat" + "gpt",
        "clau" + "de",
        "generated by " + "ai",
        "internal " + "note",
        "todo",
        "tbd",
        "placeholder",
    )
    local_user_prefix = "c:" + chr(92) + "users" + chr(92)
    local_user_prefix_forward = "c:" + "/" + "users" + "/"
    local_file_scheme = "file" + "://"
    for path in paths:
        text = path.read_text(encoding="utf-8").casefold()
        assert not any(marker in text for marker in markers)
        assert local_user_prefix not in text
        assert local_user_prefix_forward not in text
        assert local_file_scheme not in text
